@base_url=http://localhost:4000/api

# callback
###
GET {{base_url}}/auth/callback

# Register a new user
###
POST {{base_url}}/auth/register
Content-Type: application/json

{
  "email": "hello@shiplio.run",
  "password": "Password123!"
}

# Register an already existing user
###
POST {{base_url}}/auth/register
Content-Type: application/json

{
  "email": "hello@shiplio.run",
  "password": "Password123!"
}

###

# Login
###
# @name login
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "hello@shiplio.run",
  "password": "Password123!"
}

###
@token = {{login.response.body.token}}
@projectId = 1

### Upload/Deploy Project
POST {{base_url}}/projects/{{projectId}}/deployments
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="bundle.tar.gz"
Content-Type: application/x-gzip

< ./bundle.tar.gz
--boundary--

# Login with wrong password
###
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "hello@shiplio.run",
  "password": "Password123"
}


### Login with unregistered email
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "email": "wrong@shiplio.run",
  "password": "Password123!"
}

### Create Project
POST {{base_url}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "my-first-project"
}

### List Projects
GET {{base_url}}/projects
Authorization: Bearer {{token}}

