### 1. Register a new user
# @name register
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "email": "pro@shiplio.com",
  "password": "Password1234"
}

### 2. Login to get the JWT
# @name login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "pro@shiplio.com",
  "password": "Password1234"
}

###
@token = {{login.response.body.token}}

### 3. Create a project shell
# @name create_project
POST http://localhost:4000/api/projects
Authorization: Bearer {token}
Content-Type: application/json

{
  "name": "my-second-app",
  "stack": "nodejs",
  "default_port": 3000
}

###
PATCH http://localhost:4000/api/projects/70/env
Authorization: Bearer {token}

{
  "env": {
    "MY_SECRET": "supersecretvalue"
  }
}

###
@project_id = {{create_project.response.body.data.id}}

### 4. Deploy the Zip File
# Note: Ensure source.tar.gz exists in the same folder as this .rest file
POST http://localhost:4000/api/projects/{{project_id}}/deployments
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="source.tar.gz"
Content-Type: application/gzip

< ./source.tar.gz
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get Projects
GET http://localhost:4000/api/projects
Authorization: Bearer {{token}}

### Get Project Details
GET http://localhost:4000/api/projects/77
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGlwbGlvIiwiZXhwIjoxNzcxNzg4MTA0LCJpYXQiOjE3NjkxOTYxMDQsImlzcyI6InNoaXBsaW8iLCJqdGkiOiJiNGFmMjExNC01ZWZiLTQwZjUtOTEzNS1lOWFjZDAzNDQ4MWMiLCJuYmYiOjE3NjkxOTYxMDMsInN1YiI6IjEwIiwidHlwIjoiYWNjZXNzIn0.hCHgXR2FGdmWSj7lS8prQ0es8_uY6H6EZj9WVbcnmVksabjn4fNaMiKdLmgmIDa0nNCDNL55wbUg6cjktwwrkw

### Me
GET http://localhost:4000/api/auth/me
Authorization: Bearer {token}

### List Environment Variables
GET http://localhost:4000/api/projects/71/env
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGlwbGlvIiwiZXhwIjoxNzcxNzg4MTA0LCJpYXQiOjE3NjkxOTYxMDQsImlzcyI6InNoaXBsaW8iLCJqdGkiOiJiNGFmMjExNC01ZWZiLTQwZjUtOTEzNS1lOWFjZDAzNDQ4MWMiLCJuYmYiOjE3NjkxOTYxMDMsInN1YiI6IjEwIiwidHlwIjoiYWNjZXNzIn0.hCHgXR2FGdmWSj7lS8prQ0es8_uY6H6EZj9WVbcnmVksabjn4fNaMiKdLmgmIDa0nNCDNL55wbUg6cjktwwrkw
