@api_url=http://api.shiplio.lvh.me
@caddy_api = http://localhost:20200

### This ensures all project subdomains use internal certificates.
POST {{caddy_api}}/config/apps/tls/automation/policies
Content-Type: application/json

{
  "subjects": [
    "*.shiplio.lvh.me"
  ],
  "issuers": [
    {
      "module": "internal"
    }
  ]
}

### 2. Verify the TLS Configuration
GET {{caddy_api}}/config/apps/tls

### 1. Register a new user
# @name register
POST {{api_url}}/api/auth/register
Content-Type: application/json

{
  "email": "pro@shiplio.com",
  "password": "Password1234"
}

### 2. Login to get the JWT
# @name login
POST {{api_url}}/api/auth/login
Content-Type: application/json

{
  "email": "pro@shiplio.com",
  "password": "Password1234"
}

###
@token = {{login.response.body.token}}

### 3. Create a project shell
# @name create_project
POST {{api_url}}/api/projects
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGlwbGlvIiwiZXhwIjoxNzcxNzg4MTA0LCJpYXQiOjE3NjkxOTYxMDQsImlzcyI6InNoaXBsaW8iLCJqdGkiOiJiNGFmMjExNC01ZWZiLTQwZjUtOTEzNS1lOWFjZDAzNDQ4MWMiLCJuYmYiOjE3NjkxOTYxMDMsInN1YiI6IjEwIiwidHlwIjoiYWNjZXNzIn0.hCHgXR2FGdmWSj7lS8prQ0es8_uY6H6EZj9WVbcnmVksabjn4fNaMiKdLmgmIDa0nNCDNL55wbUg6cjktwwrkw
Content-Type: application/json

{
  "id": 1,
  "name": "fast-api-service",
  "status": "active",
  "stack": "python",
  "default_port": 8000,
  "dedicated_port": 4001,
  "local_url": "fast-api-service.lvh.me",
  "container_id": "d2e3f4g5h6j7k8l9",
  "env_vars": {
    "DATABASE_URL": "postgresql://user:pass@localhost:5432/db",
    "DEBUG": "false",
    "API_KEY": "sk_test_51Mz..."
  },
  "last_build_duration_ms": 12450,
  "user_id": 42,
  "inserted_at": "2026-02-05T10:00:00Z",
  "updated_at": "2026-02-05T10:30:00Z"
}

###
PATCH {{{{api_url}}}}/api/projects/70/env
Authorization: Bearer {token}

{
  "env": {
    "MY_SECRET": "supersecretvalue"
  }
}

###
@project_id = {{create_project.response.body.data.id}}

### 4. Deploy the Zip File
# Note: Ensure source.tar.gz exists in the same folder as this .rest file
POST {{api_url}}/api/projects/{{project_id}}/deployments
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="source.tar.gz"
Content-Type: application/gzip

< ./source.tar.gz
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get Projects
GET {{api_url}}/api/projects
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGlwbGlvIiwiZXhwIjoxNzcxNzg4MTA0LCJpYXQiOjE3NjkxOTYxMDQsImlzcyI6InNoaXBsaW8iLCJqdGkiOiJiNGFmMjExNC01ZWZiLTQwZjUtOTEzNS1lOWFjZDAzNDQ4MWMiLCJuYmYiOjE3NjkxOTYxMDMsInN1YiI6IjEwIiwidHlwIjoiYWNjZXNzIn0.hCHgXR2FGdmWSj7lS8prQ0es8_uY6H6EZj9WVbcnmVksabjn4fNaMiKdLmgmIDa0nNCDNL55wbUg6cjktwwrkw

### Get Project Details
GET {{api_url}}/api/projects/79
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGlwbGlvIiwiZXhwIjoxNzcxNzg4MTA0LCJpYXQiOjE3NjkxOTYxMDQsImlzcyI6InNoaXBsaW8iLCJqdGkiOiJiNGFmMjExNC01ZWZiLTQwZjUtOTEzNS1lOWFjZDAzNDQ4MWMiLCJuYmYiOjE3NjkxOTYxMDMsInN1YiI6IjEwIiwidHlwIjoiYWNjZXNzIn0.hCHgXR2FGdmWSj7lS8prQ0es8_uY6H6EZj9WVbcnmVksabjn4fNaMiKdLmgmIDa0nNCDNL55wbUg6cjktwwrkw

### Me
GET {{api_url}}/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGlwbGlvIiwiZXhwIjoxNzcxNzg4MTA0LCJpYXQiOjE3NjkxOTYxMDQsImlzcyI6InNoaXBsaW8iLCJqdGkiOiJiNGFmMjExNC01ZWZiLTQwZjUtOTEzNS1lOWFjZDAzNDQ4MWMiLCJuYmYiOjE3NjkxOTYxMDMsInN1YiI6IjEwIiwidHlwIjoiYWNjZXNzIn0.hCHgXR2FGdmWSj7lS8prQ0es8_uY6H6EZj9WVbcnmVksabjn4fNaMiKdLmgmIDa0nNCDNL55wbUg6cjktwwrkw

### List Environment Variables
GET {{api_url}}/api/projects/81/env
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGlwbGlvIiwiZXhwIjoxNzcxNzg4MTA0LCJpYXQiOjE3NjkxOTYxMDQsImlzcyI6InNoaXBsaW8iLCJqdGkiOiJiNGFmMjExNC01ZWZiLTQwZjUtOTEzNS1lOWFjZDAzNDQ4MWMiLCJuYmYiOjE3NjkxOTYxMDMsInN1YiI6IjEwIiwidHlwIjoiYWNjZXNzIn0.hCHgXR2FGdmWSj7lS8prQ0es8_uY6H6EZj9WVbcnmVksabjn4fNaMiKdLmgmIDa0nNCDNL55wbUg6cjktwwrkw


### Set Environment Variables
PATCH {{api_url}}/api/projects/81/env
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGlwbGlvIiwiZXhwIjoxNzcxNzg4MTA0LCJpYXQiOjE3NjkxOTYxMDQsImlzcyI6InNoaXBsaW8iLCJqdGkiOiJiNGFmMjExNC01ZWZiLTQwZjUtOTEzNS1lOWFjZDAzNDQ4MWMiLCJuYmYiOjE3NjkxOTYxMDMsInN1YiI6IjEwIiwidHlwIjoiYWNjZXNzIn0.hCHgXR2FGdmWSj7lS8prQ0es8_uY6H6EZj9WVbcnmVksabjn4fNaMiKdLmgmIDa0nNCDNL55wbUg6cjktwwrkw

{
  "env": {
    "MY_SECRET": "supersecretvalue"
  }
}